### ISSUE TITLE
Where can we put preliminary examinations?

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#43]
Preliminary examinations are currently hidden away in the OTP section, but this information is really important (0.62% of visits to the ICC website).

http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/Pages/communications%20and%20referrals.aspx

Consider having each country as a page in the same way as situations and indicate on the page the status of the investigation.  

Ongoing

Afghanistan
Colombia
Comoros
Federal Republic of Nigeria
Georgia
Guinea
Honduras
Republic of Korea

PE : Completed-Proceeded to Investigation
Central African Republic
Côte d’Ivoire
Darfur (Sudan)
Democratic Republic of the Congo
Kenya
Libya
Mali
Uganda

Completed-Decision not to proceed

Iraq
http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/pe-cdnp/iraq/Pages/iraq.aspx

Palestine
http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/pe-cdnp/palestine/Pages/palestine.aspx

Venezuela 
http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/pe-cdnp/venezuela/Pages/venezuela.aspx

**Comment by robertocarroll** [comment]
Updated the sitemap with a suggestion: https://github.com/robertocarroll/icc-alpha/wiki/Sitemap

**Comment by robertocarroll** [comment]
Following on from discussions with Armin, there would be a page beneath each situation for preliminary examinations, eg

afghanistan/preliminary-examination

Armin had an idea (which I didn't complete understand) to promote or demote this page depending on whether it was at the preliminary examination stage or not. 

The most important aspect (in my mind) was the ability to retain a record of the preliminary examination after the case progresses to become a situation. This would be possible with this approach.

**Comment by simmigaba** [comment]
Where does this requirement fits on situation page?

**Comment by taslaman** [comment]
So the idea is to create a subsite per country of interest (situation). So
DRC, CAR, Kenya and so on would have a second level subsite (icc-cpi.int/drc).
Now, we should treat the same all countries of interest like Iraq,
Palestine, Columbia and so on. The home pages of these situations would
have a different page layout than a fully formed situation. These would be
featured under preliminary exhaminations.

All homepages would have a selection based metadata entry which would be
used to govern one of the refiners. So when a preliminary examinations
country is promoted to a situation, the page layout of the home page is
changed to feature all the elements of the normal situation. We still need
to have a way to show all data from preliminary examinations phase.

We can maybe have two different pages for this, one for the preliminary
examinations phase and one for the situation.

The taxonomy needs to be amended to include these cases as well as the
trial stages.

I hope this make sense to you. I'll further explain this by Friday COB. I
will try to have a brief meeting with Daphne tomorrow just to dicuss this
with her.

Kind regards.
Armin.

**Comment by taslaman** [comment]
Preliminary examinations

Preliminary examinations page will be a part of the Investigations and Examinations section of the website.
The purpose of the page will be to filter the countries by the metadata (Situations phase) where the Situations phase is equal to Preliminary Examinations. The full list of entries in this metadata field will be provided by the PIDS.

The countries will be listed in the same pattern as situations. We still need to discuss if we are going to use maps or not inside the layout.

Situations and other countries

In order to create permanent placeholders for a country and have it move from one phase to another we need to create a sub-site for every country. So countries like DRC, CAR, Kenya will have a sub-site under icc-cpi.int domain, and that is true for other countries which are for any reasons not yet situations, so Iraq, Palestine, Columbia and so on.

In order to facilitate the two main phases (pre-situation and situation) of a country/conflict before the Court we need to have two different page layouts (maybe even content types). The reason behind this is the fact that we will not display the same information under situation and a pre-situation country. A pre-situation country/conflict will feature reports on activities and statements by the OTP. We also need to consult with them in case they would like to feature some further information in this section of the website.

This solves the home page of the pre-situation country. If/when a preliminary examinations country becomes a situation we should change a page layout to situations, so it would feature all information one situations need to feature. The situation phase metadata would feature one of the situations entries and this would solve the view under Investigations and Examinations section. All the previous documents in this situation from an earlier phase needs to be preserved and it would be featured at the bottom of the page (a content query web part should be featured at the bottom of the page with all the elements (reports, statements and so on) from the preliminary examinations phase). I would argue that this would be a better and cleaner way of moving a country from a preliminary examinations phase to a situation phase on our website. This section of the page needs to have its own anchor, so the possible in-page navigation would be able to display it. 

So in bullet points:

Preliminary examinations:
- country has its own sub-site under icc-ci.int
- a home page is based on a preliminary-examinations page layout.
- Metadata field situation phase is set to preliminary examination
- all supporting documentation like reports, statements, press releases and so on are featured on the page.

Preliminary examinations country becomes a situation:
- the sub-site remains the same
- the home page name remains the same
- the home page layout is changed to situations page layout
- metadata field situation phase is set to one of the situations phases
- all supporting documents from a preliminary examinations phase are featured at the bottom and a anchor link is provided to easily navigate to it.

I believe this would be an elegant way to solve this puzzle. Please let me know if this is agreeable with you.

Kind regards,
armin.

**Comment by taslaman** [comment]
Sorry for "closing" this issue. It was an error on my part.

**Comment by robertocarroll** [comment]
Great write-up! I'm clear about how this would work and will work on the layout for the PE page and the PE part of the situation page.

Simmi: does the above sound ok?

**Comment by simmigaba** [comment]
Yes this is crystal clear. Based on if a county is in PE phase or become situation, we will dynamically create page layout and will load different Web parts data accordingly. I will start working on it after the layout for PE page is defined. Though one point is not clear to me -- for Stages Page (Issue: 57), we display list of Cases across all Situations which are in Pre-Trial, Trial, etc. And you have also shown Cases Count for "Preliminary Examinations". But my understanding is that case will be filed only when PE country analysis is completed and its moved to Investigation i.e. country becomes a Situation and Case is in some logical stage like 'Pre-Trial'..So will ever there be any cases for country when its in PE phase?

**Comment by robertocarroll** [comment]
This is an important point: 

From a user perspective, preliminary examinations are an important piece of the ICC jigsaw puzzle - without them the reasons and processes for starting a situation/case are unclear. So it makes sense - in fact, I'd argue it is vital - to have them in the stages. That said, they are different and we need to make that distinction clear, ie these preliminary examinations are not cases. 

From a data/information perspective, preliminary examinations needs to show a list of the subsites which are marked as preliminary examinations in their metadata. The rest of the stages which will show a list of cases as you said. 

Does that make sense? Are there any issues with this approach? It's a matter of balancing the user needs with the technological constraints, so if we need to discuss this further, please let me know.

**Comment by simmigaba** [comment]
Technically its not an issue to display different set of data only for 'Preliminary examinations'. I can code this accordingly. Can you please expand more on:
"From a data/information perspective, preliminary examinations needs to show a list of the subsites which are marked as preliminary examinations in their metadata"

Currently for Case list, I am displaying for a particular Stage -- Case Title, Situation Title, Case Summary,  and all Accused related to that Case --- Accused Image, Accused Title, Accused Description.
So if you can please confirm what info/data you would like to see for Preliminary Examination. I guess Situation Title, Situation Summary. What else? Thanks.

**Comment by robertocarroll** [comment]
Here's the proposed layout for preliminary examinations. The examination title, eg Columbia, would be a link to the preliminary examination page for the country. 

![situation-d1-r5-pe](https://f.cloud.github.com/assets/1565953/1754499/618c4962-6652-11e3-9ea6-e03021ed3894.jpg)

**Comment by robertocarroll** [comment]
In term of order, it probably should be reverse chronological, ie latest first (which is not reflected properly in my mock-up above) to keep it consistent with cases on situation page.

**Comment by taslaman** [comment]
Thanks on this Rob. I noticed that decision-not-to-continue countries are
not listed here. Countries like Iraq, Palestine (I know it's not a country)
and so on. We should make sure that we cover all of these.

I'll try to sort taxonomy by tomorrow noon (I need to have a meeting about
it).

Kind regards.
Armin.

**Comment by robertocarroll** [comment]
Yes - that's true: clearly it's important to display the decision-not-to-continue countries somewhere, but I didn't want to confuse the issue at this stage. 

As a user, would you expect to see decision-not-to-continue countries on that page straight away or would they be another click away?

**Comment by robertocarroll** [comment]
Here's a layout with the tabs to deal with the different stages:

![situation-d1-r6-pe](https://f.cloud.github.com/assets/1565953/1763453/00b7d112-670e-11e3-9f77-ae683ecb2e13.jpg)

**Comment by robertocarroll** [comment]
Here's the link to the current preliminary examinations page:

http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/Pages/communications%20and%20referrals.aspx

This is a note for me that some of the content from this page needs to be included. 

Explanatory content on the top
Policy Paper on Preliminary Examinations can go on top as well.

Preliminary reports - convert to HTML and provide links with anchors to be linked from individual preliminary examination pages #58

**Comment by taslaman** [comment]
This is what I got from the meeting with Daphne:

 Pre-situation conflict:
- ```
       Ongoing preliminary examination
  ```
- ```
       Completed preliminary examination – Proceeded to Investigation
  ```
  
  (this should be equal as Investigations)
- ```
       Closed preliminary examination – decision not to proceed
  ```

Situation conflict:
- ```
       Investigations
  ```
- ```
       Closed
  ```

Case:
- ```
       Pre-Trial
  ```
- ```
       Trial
  ```

o   Trial preparations

o   Trial commenced
- ```
       Appeal
  ```
- ```
       Closed
  ```

I believe we need to sort the terminology of the pre-situation conflict. It
is too long for me, but maybe we can sort it later.

So we need to add these to the metadata taxonomy. Only situations,
preliminary examinations and cases pages layouts should have this taxonomy
applied.

Also, Daphne wanted to remove further clustering of the PE Ongoing, as she
said it is too complicated and quite hard to explain.

I hope this will answer more questions then raise.

Kind regards,

armin.

On Tue, Dec 17, 2013 at 3:54 PM, Robert Carroll notifications@github.comwrote:

> Here's the link to the current preliminary examinations page:
> 
> http://icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/Pages/communications%20and%20referrals.aspx
> 
> This is a note for me that some of the content from this page needs to be
> included.
> 
> Explanatory content on the top
> Policy Paper on Preliminary Examinations can go on top as well.
> 
> Preliminary reports - convert to HTML and provide links with anchors to be
> linked from individual preliminary examination pages #58https://github.com/robertocarroll/icc-alpha/issues/58
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/robertocarroll/icc-alpha/issues/43#issuecomment-30756915
> .

**Comment by robertocarroll** [comment]
Thanks for this info. This is no doubt legally accurate it, it's pretty confusing to me because of the added layer of terminology (you seem to agree, Armin?) 

How about we set it up the metadata in the way outlined above, but we don't show the user the part about "Pre-situation conflict" and "Situation conflict" which seems added unnecessary terminology? 

We just show them preliminary examinations, situations and cases - as we have it at the moment ... What do you think?

Another point: the taxonomy above is good for when situations are closed, but the word "investigations" adds more questions than it answers in my mind (as on the current site). So perhaps we only indicate when a situation is closed.

**Comment by taslaman** [comment]
Please ignore titles pre-situation conflict and situation conflict, as I
just wanted to separate the countries which are in Preliminary Examinations
from Situations.

As for the investigations, the situation cannot be in any other state than
that and closed. So it can be in Preliminary examination, investigations or
closed.

Just wanted to point that out. This might be changed at a later stage once
we show this to the working group.

**Comment by robertocarroll** [comment]
We have an approach for PEs using tabs to distinguish different status so closing this issue.
