### ISSUE TITLE
Clarification required on "Order by" feature on Case List in Situation Page

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#51]
In situation page, for "Case list (Cases)" its mentioned "Order by: Latest, A-Z, Stage". Please provide more info on this. At the moment we fetch all the Cases under a Situation and for each Case we display latest Court record.
For "Order by: Latest, A-Z, Stage" -- does it mean that all Cases under Situations have to be sorted. If so then we can implement sort logic based on "Latest" (which is Sequence number based, Every new case under situation have incremental sequence number assigned). As no two cases will have same sequence number, then whats use of further sorting by A-Z and Stage.

**Comment by robertocarroll** [comment]
I'm not sure about how important or necessary this feature is. I included it because it seemed like a good idea, but in practice it doesn't work very well: 
- A-Z: how would that work with more than one accused? 
- Latest: what would be the criteria? Latest filing? Or something else? 

The natural order - to me - feels like reverse-chronological stage: with the case at the case at the latest stage (most advanced in proceedings) at the top and then descending to the case least far along. I'm not sure how difficult that would be to achieve.

What are the other options for order of cases in a situation? I think we should pick one and leave off the ability for the user to change it.

**Comment by taslaman** [comment]
In the case we follow the hierarchy of accused. In the situations we can
have two breakdowns, one by the date of creation and one by thr stage. The
date and prder of creation can be seen in the case number which is composed
of --situation number-case number/year so in example of Lubanga it is
ICC-01/04-01/06 which means -- first situation in 2004 -- first case in
2006. In the same year a case against Ntaganda was open so the cas number
is ICC-01/04-02/06.

I hope this explains some things and if you already knew this, sorry to
have waisted your time.

Kind regards.
Armin.

**Comment by simmigaba** [comment]
Hi Armin,
Yes at every Case sub-site level we have a Sharepoint List with Case Info that stores File Number. E.g. ICC-01/04-01/06. So we will develop logic to fetch this value from all case sub-site list under Situation and then will order it by Year, Case Number (Desc). Though I am not sure about sorting by case Stage. Can you pls provide me all possible enumerated values of Case Stages in a progressive lifecycle. Then I can maintain these Enumeration values in code and also Stage field value at case level, and thereafter I should be able to develop a logic where I can also sort using Stage.

**Comment by taslaman** [comment]
Hi Simmi,

I put the list by stage because that was something Rob wanted to have that
feature. I will prepare the logic and requirements today or tomorrow,
depends on the workload I'll have today. I will also prepare all the
requirements for other list pages as well.

Kind regards.
Armin.

**Comment by robertocarroll** [comment]
Let's just have a default order and not provide any ability for the user to sort. We can revisit this idea at some point.

**Comment by taslaman** [comment]
I agree. Other views might be too much.

Kind regards,
Armin.

**Comment by robertocarroll** [comment]
Closing this issue as we have a solution.
