### ISSUE TITLE
Clarifications for Article Page

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#55]
case-page-article-d5-r1.jpg does not show how to display the related records like annexes, corrigendums, etc.
Also, is case-page-article-d5-r1.jpg the final version of requirements for article page?

**Comment by taslaman** [comment]
I'll prepare the draft of the article page by Friday COB...

**Comment by taslaman** [comment]
These are just basic requirements for the article page. It explains only
small portion of the court records display templates.

_Article page breakdown_

The theory behind this is that article page will be generated on the fly by
the usage of the Display template for court records.

_Background_

All court records will have the following hierarchy:

1    Original document in original language
2.      Original document in translatons
3.      Possible corrigenda (replaces the original docment)
4.      Annexes
5.      Annexes translations
6.      Annexes corrigenda (replaces original annexes)
7.      Related documents (documents not from this document set)

   The above hierarchy list is very important for the court records display
templates.

The original document (main document in the document set) is the trigger
for creation of the document set. All other documents in the set fall in by
the usage of the document reference number –Anx, tFra, …

Related documents (not from the set) are being identified from TRIM
directly as this information is followed and entered.

So there should be two main versions content by search web part:
1. ```
    Displaying list of court records (current index pages)
   ```
2. ```
    Displaying the relations inside the document set
   ```

_Display template_

 _To show individual court record_

Display template will create a view for the main court record in the set.
So every document number that does not contain –Anx, tFra, tEng and so on
will become a main document.

Main document will provide following metadata for the display template:
- \-        Title
- \-        Document number
- \-        Publishing Date
- \-        Source
- \-        Document Type
- \-        Case/Situation name
- \-        Case number
- -        Phase of the case.
  
  The display template will use two Content-by-search web parts to filter
  all related documents.

_To show a list of court records_

Apart from the already agreed information, I would display the translations
of the main document in the list of the court records.

_The individual court record display template (Article page)_

Based on the wireframe of the Article page (3 December 2013) these are the
fields we need to have:

_Title of the document_ (English on English part of the website and French
on the French part of the website)

_Main document number_

_Publishing date_ of the main document | _Source_ | _Document Type_

_Case name_ (official name)

Permanent three words with the _phase-of-case_ metadata entry

Div – _Download_

Content rollup web part creating links to the pdf documents of the main
document (or its corrigendum) and its translations. Use the language column
of of the attached metadata as a display text for the link.

We can maybe also have a line like: To download click on the language of
the document...

_Content by search web part_

Filter by Document number – filter everything with the first part of the
main document number excluding –corr, red, -tfra… (this does not need to be
developed now as we don't really have a drawn up system).

_Content by search web part_

Filter all documents from Related court records field in the main document
metadata field. (the same as above applies here)

I hope that this will give you at least the sense of the idea for the court
records management system. Please let me know if I'm going in the right
direction.

Kind regards,

armin.

**Comment by simmigaba** [comment]
Dear Rob,
Would it be possible for you to provide an updated wireframe (to cover any differences from the earlier one "case-page-article-d5-r1.jpg" provided by you earlier) for the artcile page based on the above inputs from Armin?
Thanks

**Comment by robertocarroll** [comment]
I think it's important to distinguish the two different approaches (and the reasons for those approaches) to the article page: 
1. As we discussed Armin envisages a possible approach using Sharepoint catalogues(?) which will allow for all the annexes, relationships between documents and much more to be generated dynamically. Everyone agrees this approach looks promising but will not be possible for the ICC Alpha. 
2. So that leave us creating a stopgap which will allow users to see the article when they click on a link in the ICC Alpha. This is what we are discussing at the moment. 

I've gone over the layout (case-page-article-d5-r1.jpg - below) and compared it with Armin's comments above and they seem to match:

"Main document will provide following metadata for the display template: - - Title - - Document number - - Publishing Date - - Source - - Document Type - - Case/Situation name - - Case number - - Phase of the case."

Below display a download section with icon and links to the various versions of the document. 

![case-page-d5-r1-article](https://f.cloud.github.com/assets/1565953/1781681/2455b8ae-689a-11e3-9243-340a061b915b.jpg)

Given that this is a stopgap, we don't need to build any more (Annexes, Corrigendum, related documents, etc) because it will be replaced. 

Does this approach seem sensible?

**Comment by simmigaba** [comment]
Sounds ok to me.

**Comment by taslaman** [comment]
It does to me. I just wanted to explain the system behind it, while
matching the requirements with the last Article page layout.

I'm sorry if I caused any confusion. Maybe I should have treated Annexes
and Corrigenda differently

Kind regards,
armin.

**Comment by robertocarroll** [comment]
Great! Closing this issue.
