### ISSUE TITLE
Use Ruto / Sang and Lubanga cases as exemplars

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-alpha#8]
Ruto / Sang has lots of different types of content which have been brought together here, while Lubanga is the case which has progressed the furthest.

**Comment by robertocarroll** [comment]
The Chui case to see a different scenario, where a case is closer to “closed”: He was in detention and was released, though the decision is in appeal. [mj]

**Comment by robertocarroll** [comment]
We need to migrate court records, press releases and multimedia for at least one case.

**Comment by simmigaba** [comment]
We are using only sample data for Lubanga case in sprint 1. 
Migration of court records, press releases, etc. from current website to ICC alpha development environment would not be feasible at this stage as the field data types in current website and ICC alpha development environment vary from each other and there is no one to one mapping hence making it difficult to migrate the content as it is. The data migration process should be dealt with separately outside ICC Alpha as this project is focusing on improving the usability of the site rather than actual data stored in the site.

**Comment by robertocarroll** [comment]
I agree the data migration is outside the scope of the ICC Alpha. I think we'll have to take it as it comes as the ICC Alpha develops and see whether there's enough information for people to be able to make informed comments with the data from a single case. 

Closing this issue for now.
