### ISSUE TITLE
Stage description Text and links

### ISSUE THREAD

**Issue by simmigaba** [robertocarroll/icc-alpha#84]
Hi Rob,
When you get time, can you please provide appropriate text for:
-- Pre-Trial, Trial, Appeal and Preliminary Examination description to be included in the respective stage pages.
-- Introductory text for 'All investigations and cases' section on HomePage
Thanks.

PS: In general also, Please let me know if you want to modify any text/ image/ video in order to make the content more appropriate for demo. In the mean time I am verifying links to Cases, Court Records on all pages to enable them wherever they are not yet proper links. Thanks.

**Comment by robertocarroll** [comment]
Here's the texts for the stages. Please can you add them. Full feedback on the stages to follow tomorrow.

Intro to stages sections
There are several stages an investigation and case must go through before a verdict is rendered. Here is one example of all of the steps an investigation and case could go through at the ICC, from start to finish: Preliminary examinations, Situations under investigation, Pre-Trial stage, Trial stage, Appeals and Closed Cases.

Preliminary examinations
Before an investigation can begin, the Office of the Prosecutor (OTP) conducts a preliminary examination to decide whether there is enough information, and whether the crimes are serious enough, to open an investigation. To open an investigation, the ICC must have jurisdiction (a Rome Statute crime appears to have been committed by a national of a Member State or on the territory of a Member State, after 1 July 2002); it must be admissible (a national court is not already dealing with it), and it must be in the interests of justice (here OTP considers whether, regardless of jurisdiction and admissibility, there is some good reason not to take on this situation.)

Situations under investigation
The Office of the Prosecutor (OTP) conducts investigations by gathering and examining evidence, questioning persons under investigation and questioning victims and witnesses, for the purpose of finding evidence of a suspect’s innocence or guilt. OTP must investigate incriminating and exonerating circumstances equally. OTP requests cooperation and assistance from States and international organisations, and also sends investigators to areas where the alleged crimes occurred to gather evidence. Investigators must be careful not to create any risk to the victims and witnesses.

Pre-trial stage
Once OTP has sufficient evidence against a suspect, it submits a request to the Pre-Trial judges to issue a warrant of arrest or summons to appear. The judges of the Pre-Trial Chamber will issue a warrant of arrest if they have good reason to believe that this person committed the crimes, and the only way to get him to trial is to arrest him because they do not believe he will show up on his own, or they have reason to believe that if he is left free he will continue committing crimes. If the judges think that the person will cooperate and come to the Court without arresting him, they can issue a summons to appear. Once either an arrest warrant or a summons to appear is issued, a case enters the Pre-Trial stage, during which the Pre-Trial Chamber judges determine whether or not there is sufficient evidence for the case to proceed to trial.

First is the initial appearance hearing. This is the first court hearing, so the first time the judges see the person face to face. The judges inform the person what the charges are, and what his rights are. The judges confirm the suspect’s identity and make sure that he understands the charges against him. Other practical issues are decided on, such as which language will be used for the hearings.  

The second major hearing is the confirmation of charges hearing, during which the Prosecution and Defence each present their case, and the legal representatives of victims present the victims’ views and concerns.  The purpose of this hearing is to determine whether the Prosecutor has enough evidence to go to trial. If she does, the judges can decide to commit the case to trial, and the suspect is then considered “the accused”. If not, the judges either decide to close the case or ask the Prosecution for additional evidence. These decisions may be appealed.

Trial stage
When a trial starts, the charges are read out to the accused, who is asked to confirm his or her understanding of the charges, and to either plead guilty or not guilty. During the trial, the Prosecution and Defence each present their cases, and the Legal Representatives of victims present the victims’ views and concerns. At the end of the trial, the judges either acquit the accused or find the accused guilty, based on the evidence. If the judges find the accused guilty, they render a verdict of guilt and a decision on the sentence. The maximum sentence is 30 years, or in extreme circumstances, life imprisonment. The judges may also render a decision on reparations for victims. The verdict and these decisions may be appealed.

Appeals stage
Both the Prosecutor and the Defence have the right to appeal a Trial Chamber’s decision if they are not happy with it. An appeal is decided on by different judges, five in total – not the same ones who gave the original verdict. The Appeals Chamber decides on the appeal, and this is the final judgment, unless it decides to send the case back to the Trial Chamber for a re-trial. Both a verdict and a sentence can be appealed.

ENDS

**Comment by robertocarroll** [comment]
Closing this issue. Looks like the texts are there, thanks.

**Comment by robertocarroll** [comment]
Re-opening issue as there's updated text for the stage intro:

There are several stages an investigation and case could go through before a verdict is rendered: Preliminary examinations, Situations under investigation, Pre-Trial stage, Trial stage, Appeals and Closed Cases.

**Comment by robertocarroll** [comment]
Closing this issue as these texts will be updated in pre-launch QA.
